### ISSUE TITLE
Research paper is not openable. 

### ISSUE THREAD

**Issue by cm2435** [lamini-ai/Lamini-Memory-Tuning#1]
First of all, really cool work by the Lamini team! 

Whilst trying to read 'research-paper.pdf' however I got the error 

```python 
Error rendering embedded code

Invalid PDF
```

so the content is not accessible

**Comment by edamamez** [comment]
Hello and thank you for your support! 🦙

There's a possibility it's due to the browser you're viewing it on, I do not see the error on my side: https://github.com/orgs/community/discussions/64419.

I have attached the paper here and am happy to email it to you if the issue persists.

[research-paper.pdf](https://github.com/user-attachments/files/15934003/research-paper.pdf) 🔗
